--return {
--  {
--    "luk400/vim-jukit",
--    config = function()
--      -- Configure vim-jukit options
--      vim.g.jukit_shell_cmd = "python3" -- Command for running Python code
--      vim.g.jukit_output_new_as_horizontal = 1 -- Use horizontal splits for outputs
--      vim.g.jukit_terminal_split_ratio = 0.4 -- Set split ratio for terminal
--      vim.g.jukit_inline_plotting = 1 -- Inline plotting
--    end,
--  },
--}
